# Generated by Django 4.2 on 2026-05-11 03:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the food item', max_length=255)),
                ('calories', models.PositiveIntegerField(help_text='Number of calories in this food item', validators=[django.core.validators.MinValueValidator(0)])),
                ('date_added', models.DateField(default=datetime.date.today, help_text='Date when this food item was consumed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['-date_added', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['date_added'], name='calorie_tra_date_ad_85fd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['created_at'], name='calorie_tra_created_2702e5_idx'),
        ),
    ]
